### ISSUE TITLE
fillnan='interpolate' options for Tseries does not work unconditionally

### ISSUE THREAD

**Issue by raoulcollenteur** [gwtsa/gwtsa#15]
The following code produces an error in optimisation when the recharge series have nan-values at the end of the beginning.

`ts1 = Tseries(recharge, Gamma(), name='recharge', fillnan='interpolate')`

This is because 'interpolate' borrowed from pandas does not fill nan-values at the beginning and end.

[This ](http://stackoverflow.com/questions/31332981/pandas-interpolation-replacing-nans-after-the-last-data-point-but-not-before-th) might be a solution?

**Comment by rubencalje** [comment]
I think we should only caluclate heads for the overlapping part of all the stress-series and the observations, and not use extrapolation of stresses. This should also be a test within GWTSA (and the GUI), which should give an error if there are no overlapping parts, or if the stresses should have started earlier before the start of observations (maybe use the 95%-time used in the simulate-method).

**Comment by raoulcollenteur** [comment]
I changed the checks routine of both the series to drop nan-values at the begin and the end in this [commit](https://github.com/gwtsa/gwtsa/commit/3fcc7c1ea43e2f545b99be441bf0558559704a30).

As for your remark Ruben, I will write an additional routine for this that is called in the simulation method to check if all the tseries and oseries can work together, but this is another issue :)
