### ISSUE TITLE
Calibration period not working when noise model is used

### ISSUE THREAD

**Issue by raoulcollenteur** [gwtsa/gwtsa#2]
There is an error when a certain calibration period is chosen in combination with a noise model. Without the noise model the model works fine.  E.g.:
`n = NoiseModel()
ml.addnoisemodel(n)
ml.solve(tmin='1965', tmax='1990')`
Gives:
`ValueError: operands could not be broadcast together with shapes (4953,) (616,) `

**Comment by mbakker7** [comment]
fixed by passing `odelt[tindex]` to noise model in solve
